### ISSUE TITLE
Re license the project to CC BY 4

### ISSUE THREAD

**Issue by darkhax** [OpenModLoader/OpenMappings#8]
The MIT license is exclusively for software, so the mappings are effectively all rights reserved right now. I would like to re license the project to [CC BY 4](https://creativecommons.org/licenses/by/4.0/). If you agree to this, please comment the following, replacing the relevant info.

> I `github user` consent to the relicensing of my contributions to Open Mappings project under CC BY 4

Please do not touch this checklist!
- [x] Darkhax
- [x] shadowfacts
- [x] coolsquid
- [x] iLexiconn
- [x] cout970
- [x] lclc98
- [x] Strikingwolf

**Comment by darkhax** [comment]
I Darkhax consent to the relicensing of my contributions to Open Mappings project under CC BY 4

**Comment by shadowfacts** [comment]
I, shadowfacts, consent to the relicensing of my contributions to the Open Mappings project under CC BY 4.

**Comment by coolsquid** [comment]
I, CoolSquid, consent to the relicensing of my contributions to the OpenMappings project under the [CC BY 4](https://creativecommons.org/licenses/by/4.0/) license.

**Comment by iLexiconn** [comment]
I, @iLexiconn, consent to the relicensing of my contributions to Open Mappings project under `CC BY 4`

**Comment by Strikingwolf** [comment]
I, Strikingwolf, consent to the relicensing of my contributions to the OpenMappings project under the [CC BY 4](https://creativecommons.org/licenses/by/4.0/) license.

**Comment by lclc98** [comment]
I, lclc98 consent to the relicensing of my contributions to Open Mappings project under CC BY 4

**Comment by cout970** [comment]
cout970 consent to the relicensing of my contributions to Open Mappings project under CC BY 4

**Comment by Thog** [comment]
Done in https://github.com/OpenModLoader/OpenMappings/commit/a798d27613e7ad2a68b018839c30d4b98baeab0a
